### ISSUE TITLE
Chimp

### ISSUE THREAD

**Issue by drewblas** [aeden/ama#2]
Why did Chimp end and what did you learn?

**Comment by aeden** [comment]
The most direct reason is that we ran out of money. There was so much that went wrong with chi.mp though, that it's worth going a bit more in depth. Before I go on though, a quick disclaimer: all of this is my opinion on what we did wrong. Had we done things differently there's still a good chance we would have failed.

First of all, we failed to develop a steadily growing stream of revenue. We had a trickle coming in near the end, mostly from customers who purchased their domain name, but we were also supporting over 100,000 non-paying users. So lesson 1: cash is king, so get that revenue flowing early.

Our second problem was that there were numerous conflicts within the company that ended up draining quite a bit of time and energy. The company was always under the control of one person, and all of the contracts were legally set up so it could never be any different, but having internal battles is a draining process. Lesson 2: hire slow, fire fast, and remember that a company succeeds when a team is united with a common purpose.

From the product side we screwed up several times. First, we built a product that was too complicated, and not just once, but twice. The first version of chi.mp never even saw the light of day because it was bug ridden and performed horribly. It tried to do too much from day 1 and failed pretty miserably. I actually had to be the one to tell the CEO a few days before we were supposed to launch, when a major event was already planned, that we were not going to be able to launch. Suffice to say, that was a dark moment. We then started off with something simple, but managed to grow it into a beast as well over a period of 9 months, and in the end it was trying to solve a problem that we were not prepared to solve. Lesson 3: build a focused product that solves the pain of a particular niche.

Finally, when we neared the end we were going all kinds of different ways, just trying to find something that would help us survive. Nothing really worked though so when it was clear that payroll was no longer going to be made, we all decided that it was time to call it quits and move on.
