### ISSUE TITLE
Thoughts on DNSSEC

### ISSUE THREAD

**Issue by drewblas** [aeden/ama#3]
What do you think of DNSSEC?  I don't think dnsimple supports DNSSEC.  Is there a reason?  Is it something you want to add in the future?

**Comment by andrewtj** [comment]
This should be a nice easy one to start with :wink:

**Comment by aeden** [comment]
> What do you think of DNSSEC?

Like most things, it has its good parts and its bad parts. It's [designed to solve very specific needs](https://tools.ietf.org/html/rfc3833), namely 1) data integrity, and 2) data origin authentication, and it seems to do that fairly well while remaining backwards compatible. When you think about the challenge of supporting backwards compatibility for a [protocol that's pretty ancient](http://tools.ietf.org/html/rfc1034), it's quite a feat.

> I don't think dnsimple supports DNSSEC. Is there a reason?

It's currently not a high priority due to the lack of demand. In addition I really want to make sure that we make the interface as easy (and automated) as possible, and thus I'm holding off implementing it until I really understand what the processes are.

Another issue that's holding it back for us is that our current registry/registrar integration channel doesn't support setting DS records at the registry. We need to get direct integration with the various registries in place to support registry-level DS records.

> Is it something you want to add in the future?

Yes. I'm not sure when it will happen, but it will most likely occur after we've done a few direct registry integrations.

FWIW, erl-dns already has a [placeholder for the implementation](https://github.com/aetrion/erl-dns/blob/master/src/erldns_dnssec.erl), and since it's open source, someone could implement that before we even get the UI/key management portion done inside DNSimple. :wink:

**Comment by aeden** [comment]
Also, in case you're interested, this is a pretty epic post on DNSSEC: http://dankaminsky.com/2011/01/05/djb-ccc/
