### ISSUE TITLE
guide me build a dns management layer using a blockchain please?

### ISSUE THREAD

**Issue by digideskio** [aeden/ama#7]
hi,

i found dnsimple amazing. I plan to steal this and build a local service at a whole different market, once  i have your consent. 

how do i build a dns management layer on dnsimple using block chains so that i can also register .bit domains and on and on?

**Comment by aeden** [comment]
Since running a domain registration and DNS service is nothing new, you wouldn't really be stealing anything from me (unless you decided to use a name similar to ours that could cause confusion, or somehow got ahold of our intellectual property), so you're welcome to build what you want.

As for how to do it with blockchains and .bit domains, you're on your own for that. I looked into it a while back but haven't looked recently. Googling for .bit domains will give you plenty of starting points to get going.

Good luck!
